language: ruby
rvm:
- 2.5.7
before_install:
- docker pull lambci/lambda:build-ruby2.5
- docker pull hashicorp/terraform:latest
- gem install bundler -v 2.0.2
install:
- bundle install --deployment
script:
- bundle exec rum plan
