#!/usr/bin/env ruby
require "dotenv/load"

rum :"brutalismbot/slack-api" do
  tag %x(git describe --tags --always).strip

  env :AWS_ACCESS_KEY_ID
  env :AWS_SECRET_ACCESS_KEY
  env :AWS_DEFAULT_REGION
  env :TF_VAR_RELEASE => tag
  env :TF_VAR_SLACK_CLIENT_ID
  env :TF_VAR_SLACK_CLIENT_SECRET
  env :TF_VAR_SLACK_OAUTH_ERROR_URI
  env :TF_VAR_SLACK_OAUTH_REDIRECT_URI
  env :TF_VAR_SLACK_OAUTH_SUCCESS_URI
  env :TF_VAR_SLACK_SIGNING_SECRET
  env :TF_VAR_SLACK_SIGNING_VERSION
  env :TF_VAR_SLACK_TOKEN

  stage :plan

  desc "Apply infrastructure"
  run :apply => :plan

  default :plan
end
